In [1]:
import pandas as pd
import numpy as np

print("Версія pandas:", pd.__version__)
print("Версія numpy:", np.__version__)

Версія pandas: 2.2.3
Версія numpy: 2.1.3


In [2]:
import pandas as pd
import io

csv_data = """id,name,category,score,money
1,Anna,A,85,1200
2,Bohdan,B,92,1500
3,Viktor,A,78,980
4,Daria,C,88,1100
5,Olena,B,95,1750
6,Ihor,A,64,800
7,Kateryna,C,90,1300
8,Maksym,B,82,1050
9,Nadiia,A,73,900
10,Oleh,C,89,1400
11,Pavlo,B,91,1600
12,Roma,A,67,850"""

df = pd.read_csv(io.StringIO(csv_data))

print("--- Перші 3 рядки ---")
display(df.head(3))

print("--- Останні 3 рядки ---")
display(df.tail(3))

--- Перші 3 рядки ---


,id,name,category,score,money
0,1,Anna,A,85,1200
1,2,Bohdan,B,92,1500
2,3,Viktor,A,78,980


--- Останні 3 рядки ---


,id,name,category,score,money
9,10,Oleh,C,89,1400
10,11,Pavlo,B,91,1600
11,12,Roma,A,67,850


In [3]:
columns_list = df.columns
print("Перелік назв колонок:", columns_list)
print("Тип змінної:", type(columns_list))

Перелік назв колонок: Index(['id', 'name', 'category', 'score', 'money'], dtype='object')
Тип змінної: <class 'pandas.core.indexes.base.Index'>


In [4]:
arr_1d = np.arange(2, 22, 2)

print("Масив:", arr_1d)
print("Сума:", arr_1d.sum())
print("Середнє:", arr_1d.mean())
print("Мінімум:", arr_1d.min())
print("Максимум:", arr_1d.max())

arr_1d_multiplied = arr_1d * 3
print("Масив, помножений на 3:", arr_1d_multiplied)

Масив: [ 2  4  6  8 10 12 14 16 18 20]
Сума: 110
Середнє: 11.0
Мінімум: 2
Максимум: 20
Масив, помножений на 3: [ 6 12 18 24 30 36 42 48 54 60]


In [5]:
np.random.seed(42)

arr_2d = np.random.randint(1, 11, size=(3, 3))
print("Двовимірний масив:\n", arr_2d)

col_sum = arr_2d.sum(axis=0)
print("\nСума за стовпцями (axis=0):", col_sum)

row_sum = arr_2d.sum(axis=1)
print("Сума за рядками (axis=1):", row_sum)

Двовимірний масив:
 [[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]

Сума за стовпцями (axis=0): [15 18 26]
Сума за рядками (axis=1): [19 22 18]


# Звіт про виконане завдання

В ході виконання практичної роботи були виконані такі кроки:
* Імпортовано бібліотеки **Pandas** та **NumPy**.
* Проаналізовано базові класи та атрибути для роботи з `DataFrame`.
* Проведено обчислення з **одновимірними** та **двовимірними** масивами NumPy.

### Переваги використання текстових комірок Markdown:
1. **Структурованість:** дозволяють розбивати код на логічні розділи за допомогою заголовків та списків.
2. **Читабельність:** використання **напівжирного**, *курсивного* форматування та формул полегшує сприйняття та документування досліджень.
3. **Інтерактивність:** перетворюють ноутбук на повноцінний інтерактивний звіт або презентацію.

In [6]:
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/data.csv'

df_drive = df.copy()

df_drive.info()

Mounted at /content/drive
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        12 non-null     int64 
 1   name      12 non-null     object
 2   category  12 non-null     object
 3   score     12 non-null     int64 
 4   money     12 non-null     int64 
dtypes: int64(3), object(2)
memory usage: 612.0+ bytes


### Порівняння типів даних:
У зчитаному наборі даних переважають такі типи:
* **int64** (числові цілі значення): для колонок `id`, `score`, `money`.
* **object** (текстові / строкові значення): для колонок `name`, `category`.

Використання методів `info()` дозволяє швидко визначити наявність пропущених значень та обсяг пам'яті, яку займає датафрейм.

In [7]:
import pandas as pd
import numpy as np

data = {
    'id': list(range(1, 11)),
    'name': ['Item_'+str(i) for i in range(1, 11)],
    'quantity': np.random.randint(10, 100, size=10),
    'money': np.random.randint(1000, 5000, size=10)
}
df = pd.DataFrame(data)
df.to_csv('test_data.csv', index=False)

## 1. Базовий огляд датафрейму



In [8]:
print("--- head() ---")
display(df.head())

print("\n--- shape ---")
print(df.shape)

print("\n--- info() ---")
df.info()

print("\n--- describe() ---")
display(df.describe())

--- head() ---


,id,name,quantity,money
0,1,Item_1,33,1955
1,2,Item_2,12,3324
2,3,Item_3,31,2184
3,4,Item_4,62,1459
4,5,Item_5,11,4385



--- shape ---
(10, 4)

--- info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        10 non-null     int64 
 1   name      10 non-null     object
 2   quantity  10 non-null     int64 
 3   money     10 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes

--- describe() ---


,id,quantity,money
count,10.00000,10.000000,10.000000
mean,5.50000,41.600000,2791.100000
std,3.02765,28.756449,1281.338749
min,1.00000,11.000000,1021.000000
25%,3.25000,16.750000,1799.000000
50%,5.50000,36.000000,2742.000000
75%,7.75000,58.250000,3759.000000
max,10.00000,97.000000,4632.000000


## 2. Перетворення колонки в масив NumPy та обчислення

In [9]:
money_array = df['money'].to_numpy()

mean_money = money_array.mean()

print("Масив money:", money_array)
print(f"Середнє значення колонки 'money': {mean_money:.2f}")

Масив money: [1955 3324 2184 1459 4385 1021 3300 1747 3904 4632]
Середнє значення колонки 'money': 2791.10
